const params = new URLSearchParams(self.location.search)
const scriptName = params.get("script")

if (!scriptName) {
  throw new Error("Missing the generated module URL in the 'script' parameter")
}

const workerUrl = new URL(self.location.href)
const scriptUrl = new URL(scriptName, workerUrl)
const workerDirectory = workerUrl.pathname.slice(0, workerUrl.pathname.lastIndexOf("/") + 1)
const scriptDirectory = scriptUrl.pathname.slice(0, scriptUrl.pathname.lastIndexOf("/") + 1)

// A worker URL is generated by the application, but keep this entry point from
// becoming a general-purpose cross-origin module loader if opened directly.
if (
  scriptUrl.origin !== workerUrl.origin ||
  scriptDirectory !== workerDirectory ||
  !scriptUrl.pathname.endsWith(".js")
) {
  throw new Error("The generated module must be a same-directory JavaScript file")
}

scriptUrl.search = ""
scriptUrl.hash = ""

try {
  const obamifyModule = await import(scriptUrl.href)
  const wasmUrl = new URL(scriptUrl.href)
  wasmUrl.pathname = wasmUrl.pathname.replace(/\.js$/, "_bg.wasm")

  await obamifyModule.default({ module_or_path: wasmUrl.href })

  // Call the worker entry explicitly. Depending on the wasm-bindgen/Trunk
  // version, importing a binary bundle does not reliably invoke Rust's main
  // function inside a module worker.
  if (typeof obamifyModule.worker_entry !== "function") {
    throw new Error("worker_entry export is missing")
  }
  obamifyModule.worker_entry()
} catch (e) {
  console.error("worker failed to initialize:", e)
  throw e
}
